"use client"
import { Button } from "@/components/ui/button";
import { Download } from "lucide-react";

const DownloadSummaryButton = ({
    title,
    summaryText,
    fileName,
    createdAt
}: {
    title?: string;
    summaryText?: string;
    fileName: string;
    createdAt?: string;
}) => {
    const handleDownload = () => {
        const summaryContent = `# ${title}\nGenerated Summary\nGenerated on: ${createdAt ? new Date(createdAt).toLocaleDateString("en-US", {
            year: 'numeric',
            month: 'long',
            day: 'numeric'
        }) : "Unknown Date"}\n${summaryText || "No summary available."}\nSource File: ${fileName}\nGenerated by SnapSumm - AI Summary Generator`;

        const blob = new Blob([summaryContent], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = `Summary-${(title || "Untitled").replace(/[^a-z0-9]/gi,'_')}.txt`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
    }
    return (
        <Button size={"sm"} className="h-8 px-3 bg-blue-100 text-blue-700 hover:bg-blue-50"
            onClick={handleDownload}
        >
            <Download className="h-4 w-4 mr-1"/>
            Download Summary
        </Button>
    )
}

export default DownloadSummaryButton;